### ISSUE TITLE
如何在docker里面运行呢

### ISSUE THREAD

**Issue by DarkAge2018** [q4w5e6/script#1]
我把jx_cfd_tx和jxTokens放在lxk项目的scripts里面
然后在jxTokens里面填入抓包得到的京喜pt_pin、pt_key
运行jx_cfd_tx就报错了
`❗️京喜财富岛提现, 错误!
SyntaxError: Unexpected token p in JSON at position 0
    at JSON.parse (<anonymous>)
    at /jd/scripts/jx_cfd_tx.js:132:48
    at Array.forEach (<anonymous>)
    at getTokens (/jd/scripts/jx_cfd_tx.js:131:30)
    at /jd/scripts/jx_cfd_tx.js:52:8
    at Object.<anonymous> (/jd/scripts/jx_cfd_tx.js:64:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)`

**Comment by q4w5e6** [comment]
？？京喜token是一个json，timestamp，phoneid和farm_jstoken组成，不同账号用&分开。

**Comment by DarkAge2018** [comment]
`let jx_tokens = [
{"timestamp": "","phoneid": "","farm_jstoken": ""}
]`
这么写没错吧，也已经校验过json格式了，还是提示京喜token格式错误
